# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_ids',
            field=models.IntegerField(),
        ),
    ]
